'use strict';
// Shared project hub: view permissions change actions, never duplicate records.
const v2Page=renderPage;
let hubTab='overview';
const hubGroups={forecast:'plan',routes:'plan','receiving-plan':'plan',sources:'plan',evidence:'documents',approvals:'documents',material:'documents',verification:'loads',deliveries:'loads',inbound:'loads',received:'loads'};
const primaryNav=[['dashboard','grid','Home'],['hub','project','Projects'],['activity','clock','Activity'],['reports','chart','Reports']];
const v3Key=testingPreview?'reground-v3-qa':'reground-v3';
try{const s=JSON.parse(localStorage.getItem(v3Key));if(s?.version===3&&s.projects?.length&&s.receivingSites?.length)state=s;}catch{}
state.version=3;
persist=()=>{try{localStorage.setItem(v3Key,JSON.stringify(state));}catch{toast('Storage is unavailable. Keep this page open to retain changes.');}};
const currentHub=()=>receiver()?(state.projects.find(p=>p.id===state.reviewProjectId)||siteProjects()[0]||project()):project();
const hubRoute=()=>receiver()?routes.find(r=>r.id===site().id):selectedRoute();
function hubAction(label,target,primary=false){return `<button class="btn ${primary?'primary':''}" data-action="hub-go" data-id="${target}">${label}</button>`;}
function sharedEvents(){const p=currentHub(),r=hubRoute();return [...p.log,...(state.receivingSites.find(s=>s.id===r.id)?.log||[])].slice(0,20);}
function sharedActivity(limit=20){const events=sharedEvents().slice(0,limit);return events.length?events.map(e=>`<div class="activity"><span class="activity-icon">${icon('clock')}</span><div><p>${esc(e.message)}</p><small>${esc(e.time)}</small></div></div>`).join(''):'<div class="quiet-empty">Your project history will appear here.<br><small>Forecast changes, evidence reviews and delivery acknowledgements stay with the project.</small></div>';}
function nextTasks(){const p=currentHub(),r=hubRoute(),checks=p.evidence[r.id],incoming=p.batches.filter(b=>b.route===r.id&&b.delivery==='In transit');let tasks=[];if(receiver()){if(!checks[5])tasks.push({title:'Review source acceptance',note:checks.slice(0,5).every(Boolean)?'Supplier evidence is ready. Check your site criteria and sign off.':'Supporting evidence still needs attention before sign-off.',owner:'Receiver',target:'approvals',ic:'file'});if(incoming.length)tasks.push({title:`Confirm ${incoming.length} incoming load${incoming.length>1?'s':''}`,note:'Check arrival, mass and your receiving record.',owner:'Receiver',target:'inbound',ic:'truck'});tasks.push({title:'Check your receiving plan',note:`${num(site().required)} t target · ${shortDate(site().start)} – ${shortDate(site().end)}`,owner:'Receiver',target:'receiving-plan',ic:'calendar'});}else{if(!checks.slice(0,5).every(Boolean))tasks.push({title:'Complete supporting evidence',note:`${checks.slice(0,5).filter(Boolean).length} of 5 supplier checks recorded.`,owner:'Supplier',target:'evidence',ic:'file'});if(!checks[5])tasks.push({title:'Receiver sign-off is pending',note:`${esc(r.name)} must review the evidence before any new load can leave.`,owner:'Receiver',target:'evidence',ic:'clock'});tasks.push({title:checks[5]?'Check and release your next load':'Prepare your next batch check',note:checks[5]?'Record field measurements. Only eligible PASS loads can be dispatched.':'You can record measurements while conditional acceptance is pending.',owner:'Supplier',target:'verification',ic:'check'});}return tasks;}
function taskList(){const tasks=nextTasks(),firstOwn=tasks.findIndex(t=>t.owner===state.role);return tasks.map((t,i)=>`<article class="hub-task"><span class="task-symbol">${icon(t.ic)}</span><div class="task-copy"><strong>${t.title}</strong><p>${t.note}</p><small>${t.owner===state.role?'Your task':t.owner+' action'} · ${esc(currentHub().name)}</small></div>${hubAction(t.owner===state.role?(i===firstOwn?'Continue':'Open'):'View status',t.target,i===firstOwn&&t.owner===state.role)}</article>`).join('');}
function projectInfo(){const p=currentHub(),r=hubRoute(),s=state.receivingSites.find(s=>s.id===r.id);return `<aside class="hub-info"><section class="panel"><div class="section-title"><h2>Project information</h2>${pill('Shared record','grey')}</div><div class="party"><span class="party-avatar">${icon('project')}</span><div><small>SUPPLIER · SOURCE</small><strong>${esc(state.profiles.Supplier.org)}</strong><span>${esc(p.name)}</span></div></div><div class="party-link">${icon('route')} ${num(r.distance)} km ${r.id===p.route?'planned route':'proposed route'}</div><div class="party"><span class="party-avatar clay">${icon('building')}</span><div><small>RECEIVER · DESTINATION</small><strong>${esc(s?.profile.org||r.name)}</strong><span>${esc(r.name)}</span></div></div><dl class="info-list"><div><dt>Material</dt><dd>${esc(p.material)}</dd></div><div><dt>Source forecast</dt><dd>${num(p.excavated-p.retained)} t</dd></div><div><dt>Haulage window</dt><dd>${shortDate(p.start)} – ${shortDate(p.end)} ${p.end.slice(0,4)}</dd></div><div><dt>Acceptance</dt><dd>${p.evidence[r.id][5]?'Conditional sign-off recorded':'Receiver review pending'}</dd></div></dl><details><summary>Team & site details</summary><p class="sub">Source: ${esc(p.location)}<br>${esc(state.profiles.Supplier.contact)}</p><p class="sub">Destination: ${esc(s?.location||r.name)}<br>${esc(s?.profile.contact||'Facility acceptance team')}</p>${hubAction('View '+(receiver()?'site requirements':'material profile'),receiver()?'receiving-plan':'material')}</details></section><div class="hub-help"><strong>Know the route before you dig.</strong><p>Reduce soil-management cost without adding programme risk.</p></div></aside>`;}
function pathway(){const p=currentHub(),r=hubRoute(),checks=p.evidence[r.id],steps=[['Forecast',true],['Match',fitsProject(r,p)],['Accept',checks.every(Boolean)],['Verify',p.batches.some(b=>b.route===r.id&&b.result==='PASS')],['Reuse',p.batches.some(b=>b.route===r.id&&b.delivery==='Delivered')]];return `<ol class="hub-path" aria-label="Project milestones">${steps.map(([name,done],i)=>`<li class="${done?'complete':''}"><span>${done?'✓':i+1}</span><strong>${name}</strong></li>`).join('')}</ol><p class="path-note">Milestones reflect recorded history. Each new load still needs a current PASS check and valid acceptance.</p>`;}
function hubOverview(home=false){const p=currentHub(),r=hubRoute(),bs=p.batches.filter(b=>b.route===r.id),delivered=bs.filter(b=>b.delivery==='Delivered').reduce((n,b)=>n+b.mass,0),incoming=bs.filter(b=>b.delivery==='In transit').reduce((n,b)=>n+b.mass,0);return `<div class="hub-layout"><div class="hub-body"><section class="hub-stats"><div><span>${receiver()?'Site material still needed':'Source surplus forecast'}</span><strong>${num(receiver()?Math.max(0,site().required-receivedMass()-transitMass()):p.excavated-p.retained)}<small> t</small></strong><small>${receiver()?'Target minus received and incoming':'Planning estimate'}</small></div><div><span>${receiver()?'Received at this site':'Received on this route'}</span><strong>${num(receiver()?receivedMass():delivered)}<small> t</small></strong><small>Acknowledged loads</small></div><div><span>In transit ${receiver()?'to this site':'on this route'}</span><strong>${num(receiver()?transitMass():incoming)}<small> t</small></strong><small>Awaiting receipt</small></div></section><section class="panel"><div class="section-title"><h2>Up next</h2><span class="sub">${state.role} tasks</span></div>${taskList()}</section><section class="panel"><div class="section-title"><h2>${esc(p.name)}</h2>${hubAction('Open project','hub')}</div>${pathway()}<div class="shared-note">${icon('building')} Both teams see the same route, evidence status and load records.</div></section><section class="panel"><div class="section-title"><h2>Recent activity</h2>${hubAction('View history','activity')}</div>${sharedActivity(5)}</section></div>${projectInfo()}</div>`;}
function projectTabs(){const tabs=[['overview','Overview'],['plan','Plan & route'],['documents','Evidence'],['loads','Loads']];return `<nav class="hub-tabs" aria-label="Project sections">${tabs.map(([id,label])=>`<button data-action="hub-tab" data-id="${id}" ${id===hubTab?'aria-current="page"':''} class="${id===hubTab?'selected':''}">${label}</button>`).join('')}</nav>`;}
function subTools(){const options=hubTab==='plan'?(receiver()?[['receiving-plan','My site criteria'],['sources','Find sources']]:[['routes','Compare routes'],['forecast','Edit forecast']]):hubTab==='documents'?(receiver()?[['approvals','Review acceptance']]:[['evidence','Evidence checklist'],['material','Material profile']]):hubTab==='loads'?(receiver()?[['inbound','Incoming'],['received','Received']]:[['deliveries','Track loads'],['verification','Check a batch']]):[];return `<div class="hub-subtools">${options.map(([id,label])=>`<button data-action="hub-go" data-id="${id}" class="${page===id?'selected':''}">${label}</button>`).join('')}</div>`;}
function hubContent(){if(page==='dashboard')return heading('YOUR WORKSPACE','Home','Your next actions and shared project records.')+hubOverview(true);if(page==='activity')return heading('SHARED PROJECT HISTORY','Activity','Source changes, receiver decisions and delivery records in one place.')+`<div class="hub-layout"><section class="panel">${sharedActivity()}</section>${projectInfo()}</div>`;if(page==='reports')return receiver()?receiverImpact():impactPage();const p=currentHub();let content=page==='hub'?hubOverview():v2Page();if(page!=='hub')content=content.replace(/<h1>/g,'<h2 class="task-heading">').replace(/<\/h1>/g,'</h2>');if(page==='routes')content=content.replace(/<div class="route-facts">([\s\S]*?)<\/div><div class="progress-label">/g,'<details class="route-detail"><summary>Cost, capacity & dates</summary><div class="route-facts">$1</div></details><div class="progress-label">');if(page==='receiving-plan')content=content.replace('<fieldset class="criteria-fieldset">','<details class="advanced-criteria"><summary>Technical acceptance limits</summary><fieldset class="criteria-fieldset">').replace('</fieldset>','</fieldset></details>');return `<div class="hub-title"><div><div class="eyebrow">SHARED PROJECT · ${esc(p.id)}</div><h1>${esc(p.name)}</h1><p>${esc(p.location)} · ${esc(p.material)}</p></div>${!receiver()?button('New project','new-project'):''}</div>${projectTabs()}${hubTab!=='overview'?`<div class="partner-strip"><span>${icon('project')} ${esc(state.profiles.Supplier.org)}</span><span>→</span><span>${icon('building')} ${esc(state.receivingSites.find(s=>s.id===hubRoute().id)?.profile.org||hubRoute().name)}</span><small>Shared project · ${state.role} actions</small></div>`:''}${hubTab!=='overview'?subTools():''}${content}`;}
render=function(){syncRoutes();document.title='ReGround V3 — Shared project workspace';const active=primaryNav.some(n=>n[0]===page)?page:'hub',prof=workspaceProfile();$('#app').innerHTML=`<aside id="workspace-navigation" class="sidebar hub-sidebar ${navOpen?'open':''}" ${navOpen?'role="dialog" aria-modal="true"':''} aria-label="Main navigation"><div class="brand"><span class="brandmark">»</span>ReGround<span class="version-mark">V3</span></div><button class="drawer-close" data-action="close-nav" aria-label="Close navigation">×</button><div class="hub-org"><strong>${esc(prof.org)}</strong><small>${state.role==='Supplier'?'Source team':'Receiving team'}</small></div><nav class="nav">${primaryNav.map(([id,ic,label])=>`<button data-action="hub-go" data-id="${id}" class="${id===active?'active':''}" ${id===active?'aria-current="page"':''}>${icon(ic)}<span>${label}</span></button>`).join('')}</nav><div class="sidebar-bottom"><button class="user-btn" data-action="profile-edit">${icon('building')}<span>Organisation settings<small>${state.role} details</small></span></button><small class="hub-demo">Local prototype · Saved on this device</small></div></aside>${navOpen?'<button class="nav-scrim" data-action="close-nav" aria-label="Close navigation overlay"></button>':''}<div class="shell" ${navOpen?'inert':''}><header class="topbar hub-top"><button class="mobile-menu" data-action="menu" aria-label="Open navigation" aria-expanded="${navOpen}" aria-controls="workspace-navigation">${icon('menu')}</button><div class="hub-context"><label>${receiver()?'Receiving site':'Source project'}${receiver()?`<select id="site-select" aria-label="Receiving site">${state.receivingSites.map(s=>`<option value="${s.id}" ${site().id===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select>`:`<select id="project-select" aria-label="Source project">${state.projects.map(p=>`<option value="${esc(p.id)}" ${p.id===project().id?'selected':''}>${esc(p.name)}</option>`).join('')}</select>`}</label></div><div class="hub-role" role="group" aria-label="Preview working role"><span>Viewing as</span><button data-action="set-role" data-id="Supplier" aria-pressed="${!receiver()}" class="${!receiver()?'selected':''}">Supplier</button><button data-action="set-role" data-id="Receiver" aria-pressed="${receiver()}" class="${receiver()?'selected':''}">Receiver</button></div></header><main id="main" class="main hub-main" tabindex="-1">${hubContent()}<footer class="footer-note"><span>ReGround V3 · Illustrative Auckland project</span><span>Local demo · Shared on this browser only · NZD excl. GST</span></footer></main></div>`;if(navOpen)setTimeout(()=>$('.drawer-close')?.focus(),0);};
navigate=function(next){navOpen=false;page=next;hubTab=hubGroups[next]||'overview';if(!receiver()&&next==='evidence')routeFocus=project().route;state.lastPages[state.role]=next;persist();render();window.scrollTo({top:0});$('#main').focus({preventScroll:true});};
switchWorkspace=function(role,next){if(!['Supplier','Receiver'].includes(role))return;state.role=role;state.org=workspaceProfile().org;routeFocus=receiver()?site().id:project().route;batchResult=null;navigate(next||'dashboard');toast(role+' view. The same project records are retained.');};
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='hub-go'){e.stopImmediatePropagation();navigate(b.dataset.id);}if(b.dataset.action==='hub-tab'){e.stopImmediatePropagation();const t=b.dataset.id;if(t==='overview')navigate('hub');else navigate(t==='plan'?(receiver()?'receiving-plan':'routes'):t==='documents'?(receiver()?'approvals':'evidence'):(receiver()?'inbound':'deliveries'));}},true);
// Any legacy action that changes page gets the matching project section on render.
const hubRender=render;render=function(){if(hubGroups[page])hubTab=hubGroups[page];hubRender();};
page='dashboard';persist();render();
